### ISSUE TITLE
[Question]: why not hangeul but hangul?

### ISSUE THREAD

**Issue by roeniss** [toss/es-hangul#70]
It seems that the correct romanization for 한글 is Hangeul. Is there any particular reason to use Hangul?

**Comment by roeniss** [comment]
reference: https://nl.go.kr/nlcol/html/data0007.htm

**Comment by 99mini** [comment]
Hi @roeniss!

I find additional reference that `Hangeul` is correct, not `Hangul`. [[hangeul과 hangul, 어떤 것이 정확한 표현일까요? - 국립국어원 답변](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=277596&pageIndex=1&searchCondition=qsubject&searchKeyword=hangeul)] But, some agency use `Hangul` instead of `Hangeul`. [[국민민속박물관 - 영문 페이지](https://www.nfm.go.kr/k-box/ui/annyeong/hangeul.do;jsessionid=EFFD4D46C9F46C9EA581D6EAA8893429?lang=en)]

Perhaps `Hangeul` is correct, but it is also possible to use `Hangul`.

**Comment by roeniss** [comment]
Hi, 99mini! Thank you for additional references.

Ironically, the second URL you provided also contains 'Hangeul'.

**Comment by surri** [comment]
Interesting.
`hangul` is the `McCune–Reischauer Romanization` of 한글.
It was used in 대한민국 until 2000, and was replaced by `hangeul` using the `Revised Romanization(개정 로마자 표기법)`.

I think "Kim" and "Park" could be used instead of the current standard "gim" and "bak".
Because, it's not mandatory.

But, I believe using the standard would reduce confusion for everyone.

**Comment by roeniss** [comment]
> But, some government agencies use Hangul instead of Hangeul. [[국립민속박물관 - 영문 페이지](https://www.nfm.go.kr/k-box/ui/annyeong/hangeul.do;jsessionid=EFFD4D46C9F46C9EA581D6EAA8893429?lang=en)] 

@99mini Do you have other examples too? The page you gave is fixed now.

**Comment by okinawaa** [comment]
First of all, I'm sorry for the late response, and thank you for suggesting a new perspective.

According to the correct grammar rules, I think `Hangeul` is right as the roeniss said.
However, I think foreigners are more familiar with using `hangul` than `hangeul`.

I searched on Google, and there were about 38 million search results for `hangul` and 5 million search results for hangeul. 

If I had known the difference between the two before the library was made, I would have been able to think about it, but now We are communicating with `Hangul`, so if there's no big reason to change it, I'd like to keep it current.

If the same problem comes up in the future, why don't we try one more revisit?

**Comment by roeniss** [comment]
> why don't we try one more revisit?

Of course it's on your decision and I'm enough with your opinion now. Feel free to close this. @okinawaa

**Comment by youngjae99** [comment]
Thank you for your feedback @roeniss :)
